### ISSUE TITLE
schema html parsing?

### ISSUE THREAD

**Issue by aperz** [ProteinsWebTeam/ebi-metagenomics-cwl#77]
I was trying to use a simple workflow to test the package, run into a problem with the schema not being read in correctly. Seems like it does not parse the html file, rather, it reads it in literally. Is it a known issue? Am I doing something incorrectly?

```bash
/P/cwl/venv/bin/cwltool 1.0.20180615183820
Resolved 'ebi-metagenomics-cwl/tools/trimmomatic.cwl' to 'file:///P/cwl/ebi-metagenomics-cwl/tools/trimmomatic.cwl'
https://schema.org/docs/!DOCTYPE html does not look like a valid URI, trying to serialize this will break.
https://schema.org/docs/html lang="en" does not look like a valid URI, trying to serialize this will break.
I'm sorry, I couldn't load this CWL file.
The error was: 
```
```python
Traceback (most recent call last):
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/main.py", line 478, in main
    metadata, uri, loadingContext)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/load_tool.py", line 342, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/workflow.py", line 45, in default_make_tool
    return command_line_tool.CommandLineTool(toolpath_object, loadingContext)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/command_line_tool.py", line 217, in __init__
    toolpath_object, loadingContext)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/process.py", line 559, in __init__
    validate_js_expressions(cast(CommentedMap, toolpath_object), self.doc_schema.names[toolpath_object["class"]], validate_js_options)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/validate_js.py", line 181, in validate_js_expressions
    expressions = get_expressions(tool, schema)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/validate_js.py", line 76, in get_expressions
    SourceLine(tool, schema_field.name)
  File "/P/cwl/venv/lib/python3.6/site-packages/cwltool/validate_js.py", line 55, in get_expressions
    assert valid_schema is not None
AssertionError
```

**Comment by mr-c** [comment]
Hello @aperz , thank you for reporting the error you experienced. It is a bug with `cwltool` and I have a fix for it over at https://github.com/common-workflow-language/cwltool/pull/801
